### ISSUE TITLE
Not support drawableStart

### ISSUE THREAD

**Issue by jinzhaoyu** [pnc/IconButton#10]
My application's minsdk is 17, and in my layout xml file, i used drawableStart only , not set drawableLeft。Than IconButton does not working!

**Comment by pnc** [comment]
Hi! This library is pretty old-school and only supports `drawableLeft` and `drawableRight`, per the README. I don't currently have the time to add support for other drawables, but I'll happily review and accept a pull request that adds support for `drawableStart`.
