### ISSUE TITLE
if icons of different sizes are used, then the larger icon must be used for calculations

### ISSUE THREAD

**Issue by kaushikgopal** [pnc/IconButton#6]
Try this as an example: 

```
    <com.phillipcalvin.iconbutton.IconButton
        android:id="@+id/IconButton07"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:paddingTop="40dp"
        android:paddingBottom="40dp"
        android:text="@string/icon_both_padding"
        android:drawableLeft="@drawable/ic_launcher"
        android:drawableRight="@drawable/action_search"
        app:iconPadding="10dp"
        />
```

**Comment by pnc** [comment]
@kaushikgopal Makes a lot of sense. I don't have a working Android environment right now, but I'll try to put together a fix at some point.

**Comment by pnc** [comment]
I never needed this functionality personally (nor have I had to install Android Studio) so I'm closing this for now. Feel free to re-open it as a pull request if you added this logic and I'll get it merged!
